# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tunde.oladipupo/Documents/dev/blockchain/bitcoinaeon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tunde.oladipupo/Documents/dev/blockchain/bitcoinaeon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.10.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tunde.oladipupo/Documents/dev/blockchain/bitcoinaeon/CMakeFiles /Users/tunde.oladipupo/Documents/dev/blockchain/bitcoinaeon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tunde.oladipupo/Documents/dev/blockchain/bitcoinaeon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f CMakeFiles/version.dir/build.make CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named libminiupnpc-static

# Build rule for target.
libminiupnpc-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libminiupnpc-static
.PHONY : libminiupnpc-static

# fast build rule for target.
libminiupnpc-static/fast:
	$(MAKE) -f external/miniupnpc/CMakeFiles/libminiupnpc-static.dir/build.make external/miniupnpc/CMakeFiles/libminiupnpc-static.dir/build
.PHONY : libminiupnpc-static/fast

#=============================================================================
# Target rules for targets named wallet

# Build rule for target.
wallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wallet
.PHONY : wallet

# fast build rule for target.
wallet/fast:
	$(MAKE) -f src/CMakeFiles/wallet.dir/build.make src/CMakeFiles/wallet.dir/build
.PHONY : wallet/fast

#=============================================================================
# Target rules for targets named connectivity-tool

# Build rule for target.
connectivity-tool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 connectivity-tool
.PHONY : connectivity-tool

# fast build rule for target.
connectivity-tool/fast:
	$(MAKE) -f src/CMakeFiles/connectivity-tool.dir/build.make src/CMakeFiles/connectivity-tool.dir/build
.PHONY : connectivity-tool/fast

#=============================================================================
# Target rules for targets named daemon

# Build rule for target.
daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemon
.PHONY : daemon

# fast build rule for target.
daemon/fast:
	$(MAKE) -f src/CMakeFiles/daemon.dir/build.make src/CMakeFiles/daemon.dir/build
.PHONY : daemon/fast

#=============================================================================
# Target rules for targets named simpleminer

# Build rule for target.
simpleminer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simpleminer
.PHONY : simpleminer

# fast build rule for target.
simpleminer/fast:
	$(MAKE) -f src/CMakeFiles/simpleminer.dir/build.make src/CMakeFiles/simpleminer.dir/build
.PHONY : simpleminer/fast

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) -f src/CMakeFiles/crypto.dir/build.make src/CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f src/CMakeFiles/common.dir/build.make src/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named bsimplewallet

# Build rule for target.
bsimplewallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bsimplewallet
.PHONY : bsimplewallet

# fast build rule for target.
bsimplewallet/fast:
	$(MAKE) -f src/CMakeFiles/bsimplewallet.dir/build.make src/CMakeFiles/bsimplewallet.dir/build
.PHONY : bsimplewallet/fast

#=============================================================================
# Target rules for targets named ringct

# Build rule for target.
ringct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ringct
.PHONY : ringct

# fast build rule for target.
ringct/fast:
	$(MAKE) -f src/CMakeFiles/ringct.dir/build.make src/CMakeFiles/ringct.dir/build
.PHONY : ringct/fast

#=============================================================================
# Target rules for targets named rpc

# Build rule for target.
rpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpc
.PHONY : rpc

# fast build rule for target.
rpc/fast:
	$(MAKE) -f src/CMakeFiles/rpc.dir/build.make src/CMakeFiles/rpc.dir/build
.PHONY : rpc/fast

#=============================================================================
# Target rules for targets named cryptonote_core

# Build rule for target.
cryptonote_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptonote_core
.PHONY : cryptonote_core

# fast build rule for target.
cryptonote_core/fast:
	$(MAKE) -f src/CMakeFiles/cryptonote_core.dir/build.make src/CMakeFiles/cryptonote_core.dir/build
.PHONY : cryptonote_core/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named net_load_tests_srv

# Build rule for target.
net_load_tests_srv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_load_tests_srv
.PHONY : net_load_tests_srv

# fast build rule for target.
net_load_tests_srv/fast:
	$(MAKE) -f tests/CMakeFiles/net_load_tests_srv.dir/build.make tests/CMakeFiles/net_load_tests_srv.dir/build
.PHONY : net_load_tests_srv/fast

#=============================================================================
# Target rules for targets named net_load_tests_clt

# Build rule for target.
net_load_tests_clt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_load_tests_clt
.PHONY : net_load_tests_clt

# fast build rule for target.
net_load_tests_clt/fast:
	$(MAKE) -f tests/CMakeFiles/net_load_tests_clt.dir/build.make tests/CMakeFiles/net_load_tests_clt.dir/build
.PHONY : net_load_tests_clt/fast

#=============================================================================
# Target rules for targets named unit-tests

# Build rule for target.
unit-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit-tests
.PHONY : unit-tests

# fast build rule for target.
unit-tests/fast:
	$(MAKE) -f tests/CMakeFiles/unit-tests.dir/build.make tests/CMakeFiles/unit-tests.dir/build
.PHONY : unit-tests/fast

#=============================================================================
# Target rules for targets named crypto-tests

# Build rule for target.
crypto-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypto-tests
.PHONY : crypto-tests

# fast build rule for target.
crypto-tests/fast:
	$(MAKE) -f tests/CMakeFiles/crypto-tests.dir/build.make tests/CMakeFiles/crypto-tests.dir/build
.PHONY : crypto-tests/fast

#=============================================================================
# Target rules for targets named hash-target-tests

# Build rule for target.
hash-target-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash-target-tests
.PHONY : hash-target-tests

# fast build rule for target.
hash-target-tests/fast:
	$(MAKE) -f tests/CMakeFiles/hash-target-tests.dir/build.make tests/CMakeFiles/hash-target-tests.dir/build
.PHONY : hash-target-tests/fast

#=============================================================================
# Target rules for targets named performance-tests

# Build rule for target.
performance-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 performance-tests
.PHONY : performance-tests

# fast build rule for target.
performance-tests/fast:
	$(MAKE) -f tests/CMakeFiles/performance-tests.dir/build.make tests/CMakeFiles/performance-tests.dir/build
.PHONY : performance-tests/fast

#=============================================================================
# Target rules for targets named core-proxy

# Build rule for target.
core-proxy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core-proxy
.PHONY : core-proxy

# fast build rule for target.
core-proxy/fast:
	$(MAKE) -f tests/CMakeFiles/core-proxy.dir/build.make tests/CMakeFiles/core-proxy.dir/build
.PHONY : core-proxy/fast

#=============================================================================
# Target rules for targets named difficulty-tests

# Build rule for target.
difficulty-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 difficulty-tests
.PHONY : difficulty-tests

# fast build rule for target.
difficulty-tests/fast:
	$(MAKE) -f tests/CMakeFiles/difficulty-tests.dir/build.make tests/CMakeFiles/difficulty-tests.dir/build
.PHONY : difficulty-tests/fast

#=============================================================================
# Target rules for targets named functional-tests

# Build rule for target.
functional-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 functional-tests
.PHONY : functional-tests

# fast build rule for target.
functional-tests/fast:
	$(MAKE) -f tests/CMakeFiles/functional-tests.dir/build.make tests/CMakeFiles/functional-tests.dir/build
.PHONY : functional-tests/fast

#=============================================================================
# Target rules for targets named hash-tests

# Build rule for target.
hash-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash-tests
.PHONY : hash-tests

# fast build rule for target.
hash-tests/fast:
	$(MAKE) -f tests/CMakeFiles/hash-tests.dir/build.make tests/CMakeFiles/hash-tests.dir/build
.PHONY : hash-tests/fast

#=============================================================================
# Target rules for targets named coretests

# Build rule for target.
coretests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coretests
.PHONY : coretests

# fast build rule for target.
coretests/fast:
	$(MAKE) -f tests/CMakeFiles/coretests.dir/build.make tests/CMakeFiles/coretests.dir/build
.PHONY : coretests/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f tests/gtest/CMakeFiles/gtest_main.dir/build.make tests/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f tests/gtest/CMakeFiles/gtest.dir/build.make tests/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... version"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... test"
	@echo "... libminiupnpc-static"
	@echo "... wallet"
	@echo "... connectivity-tool"
	@echo "... daemon"
	@echo "... simpleminer"
	@echo "... crypto"
	@echo "... common"
	@echo "... bsimplewallet"
	@echo "... ringct"
	@echo "... rpc"
	@echo "... cryptonote_core"
	@echo "... tests"
	@echo "... net_load_tests_srv"
	@echo "... net_load_tests_clt"
	@echo "... unit-tests"
	@echo "... crypto-tests"
	@echo "... hash-target-tests"
	@echo "... performance-tests"
	@echo "... core-proxy"
	@echo "... difficulty-tests"
	@echo "... functional-tests"
	@echo "... hash-tests"
	@echo "... coretests"
	@echo "... gtest_main"
	@echo "... gtest"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

